### PR TITLE
Fix invalid html, match the style

### PR DESCRIPTION
**Pull request by haruair**
I just saw a minor thing, please review this PR. Thanks for your work.

### CODE REVIEW

**Comment by nishanths** [comment]
thanks @haruair! happy to merge. 

can you make the css changes to `dev/less` and run the less compiler? https://github.com/nishanths/cocoa-hugo-theme/tree/master/dev

**Comment by nishanths** [comment]
related lines: https://github.com/nishanths/cocoa-hugo-theme/blob/master/dev/less/site.less#L147

**Comment by haruair** [comment]
I just updated the less file. Please review the changes. 😄

**Comment by nishanths** [comment]
thanks!

**Pull request merged**
