### PR TITLE
add HTML5 style favicon

### PR DESCRIPTION
**Pull request by mikoim**
This PR adds HTML5 style favicon for modern browsers. It can use a bigger image as favicon.

### CODE REVIEW

**Comment by mikoim** [comment]
Can `<link rel="shortcut icon" href="..">` be removed with same reason?
https://github.com/nishanths/cocoa-hugo-theme/pull/81#issuecomment-298675702

**Comment by lpancescu** [comment]
I wouldn't remove it, since iOS Safari is able to use it as a bookmark icon.

https://css-tricks.com/favicon-quiz/

**Comment by mikoim** [comment]
Confirmed. I tested behavior on [this page](https://github.com/mikoim/cocoa-hugo-theme/blob/test-favicon/index.html), definitely Safari (iOS 10.3.1) uses `ref="shortcut icon"`.

**Comment by lpancescu** [comment]
Looking at your patch again, iOS Safari wouldn't be able to use the PNG, but also not the .ICO, because it's hidden inside a comment. Perhaps it would be worth having a look at how [HTML5 Boilerplate][h5bp] does it.

[h5bp]: https://html5boilerplate.com/

**Comment by mikoim** [comment]
In HTML5 Boilerplate, `<link rel="icon">` and `<link rel="shortcut icon">` are not used. It rely on browser behavior and except that favicon.ico exists on root directory. So I close this PR, it useless.

**Pull request closed without merging**
