### PR TITLE
Organize content in arbitrary sections

### PR DESCRIPTION
**Pull request by lpancescu**
Hugo expects the content to be organized in [arbitrary sections][1]. We
can keep the structure of the demo site if we use the same default
template for list and single content, and override for the blog list and
index pages. This will get rid of the unnecessary fixed directory in the
generated output, arbitrary sections (optionally containing other
items), as well as automatically generated menus.

@nishanths This will break existing sites, please feel free to reject the patch.

[1]: http://gohugo.io/overview/source-directory/

### CODE REVIEW

**Comment by nishanths** [comment]
will look at during the weekend, @lpancescu! sorry about the delay :)

**Comment by lpancescu** [comment]
No problem, I forgot to remove the permalink for the now-deleted `fixed` section from the demo config.toml anyway...

**Comment by lpancescu** [comment]
@nishanths Did you get the chance of going through the proposed changes?

**Comment by nishanths** [comment]
This is awesome!

**Pull request merged**
